{
 "title": "Meal Mentor Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Question / Answer",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    question AS \"Question\",\n    answer AS \"Answer\"\nFROM\n    conversations\nORDER BY\n    timestamp DESC;\n"
    }
   ]
  },
  {
   "title": "Most Frequent Keywords in Questions",
   "type": "table",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT word, COUNT(*) as frequency\nFROM (\n    SELECT unnest(string_to_array(lower(regexp_replace(question, '[^a-zA-Z0-9\\s]', '', 'g')), ' ')) as word\n    FROM conversations\n) sub\nGROUP BY word\nORDER BY frequency DESC\nLIMIT 50;"
    }
   ]
  },
  {
   "title": "Average Response Time Over Time By Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "SELECT DATE(timestamp) as date, AVG(response_time) as \"Average Response Time\"\nFROM conversations\nGROUP BY DATE(timestamp)\nORDER BY DATE(timestamp);"
    }
   ]
  },
  {
   "title": "Relevance Ratings Over Time By Hour",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('hour', timestamp) AS \"Hour\",  -- Truncate timestamp to the hour\n  AVG(\n    CASE relevance\n      WHEN 'RELEVANT' THEN 1\n      WHEN 'PARTLY_RELEVANT' THEN 0\n      WHEN 'NON_RELEVANT' THEN -1\n      ELSE 0  -- Assigns 0 for any unexpected or NULL values\n    END\n  ) AS \"Average Relevance\"\nFROM conversations\nWHERE timestamp IS NOT NULL\nGROUP BY DATE_TRUNC('hour', timestamp)  -- Group by truncated hour\nORDER BY DATE_TRUNC('hour', timestamp);\n"
    }
   ]
  },
  {
   "title": "Average Response Time Last 10 Requests (s)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 27 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AVG(response_time) AS \"Average Response Time of Last 10 Requests\"\nFROM (\n  SELECT\n    response_time,\n    ROW_NUMBER() OVER (ORDER BY timestamp DESC) AS row_num\n  FROM conversations\n) AS numbered_requests\nWHERE row_num <= 10;\n"
    }
   ]
  },
  {
   "title": "Feedback Ratings Distribution",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \n    CASE \n        WHEN feedback > 0 THEN 'Positive' \n        WHEN feedback < 0 THEN 'Negative' \n        ELSE 'Neutral' \n    END as feedback_type,\n    COUNT(*) as \"Count\"\nFROM feedback\nGROUP BY feedback_type;"
    }
   ]
  },
  {
   "title": "Feedback Submission Over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(timestamp, 'YYYY-MM-DD') AS \"Date\",  -- Formats timestamp to 'YYYY-MM-DD'\n  COUNT(*) AS \"Feedback Count\"\nFROM feedback\nGROUP BY TO_CHAR(timestamp, 'YYYY-MM-DD')\nORDER BY TO_CHAR(timestamp, 'YYYY-MM-DD');\n"
    }
   ]
  },
  {
   "title": "Retrieved Document Relevancy Share",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 7, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "\nSELECT\n  COUNT(CASE WHEN relevance = 'RELEVANT' THEN 1 END) AS \"RELEVANT\",\n  COUNT(CASE WHEN relevance = 'PARTLY_RELEVANT' THEN 1 END) AS \"PARTLY_RELEVANT\",\n  COUNT(CASE WHEN relevance = 'NON_RELEVANT' THEN 1 END) AS \"NON_RELEVANT\"\nFROM conversations\n"
    }
   ]
  },
  {
   "title": "Model Usage Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 17, "x": 7, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT model_used, COUNT(*) as usage_count\nFROM conversations\nGROUP BY model_used;"
    }
   ]
  },
  {
   "title": "Total OpenAI Cost Over Time By Day",
   "type": "table",
   "gridPos": { "h": 14, "w": 7, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(timestamp, 'YYYY-MM-DD') AS \"Date\",  -- Formats timestamp to 'YYYY-MM-DD'\n  SUM(openai_cost) AS \"Total Cost\"\nFROM conversations\nGROUP BY TO_CHAR(timestamp, 'YYYY-MM-DD')   -- Group by formatted date\nORDER BY TO_CHAR(timestamp, 'YYYY-MM-DD');  -- Order by formatted date\n"
    }
   ]
  },
  {
   "title": "Average Tokens Used Per Conversation",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 7, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(timestamp, 'YYYY-MM-DD') AS \"Date\",  -- Formats timestamp to 'YYYY-MM-DD'\n  AVG(total_tokens) AS \"Average Tokens\"\nFROM conversations\nGROUP BY TO_CHAR(timestamp, 'YYYY-MM-DD')   -- Group by formatted date\nORDER BY TO_CHAR(timestamp, 'YYYY-MM-DD');  -- Order by formatted date\n"
    }
   ]
  },
  {
   "title": "Conversations Over Time By Date",
   "type": "table",
   "gridPos": { "h": 14, "w": 6, "x": 13, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  TO_CHAR(timestamp, 'YYYY-MM-DD') AS \"Date\",  -- Formats timestamp to 'YYYY-MM-DD'\n  COUNT(*) AS \"Conversation Count\"      -- Corrected alias without single quotes\nFROM conversations\nGROUP BY TO_CHAR(timestamp, 'YYYY-MM-DD')      -- Group by formatted date\nORDER BY TO_CHAR(timestamp, 'YYYY-MM-DD');     -- Order by formatted date\n"
    }
   ]
  },
  {
   "title": "Correlation Between Feedback and Response Time",
   "type": "table",
   "gridPos": { "h": 14, "w": 5, "x": 19, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n  c.response_time AS \"Response Time\",\n  f.feedback AS \"Feedback Score\"\nFROM feedback f\nJOIN conversations c ON f.conversation_id = c.id\nORDER BY c.timestamp DESC;  -- Orders by the most recent timestamp in descending order\n"
    }
   ]
  }
 ]
}